### ISSUE TITLE
Undefined Constant 'WP_DEBUG'

### ISSUE THREAD

**Issue by philiprabbett** [nlemoine/timber-dump-extension#2]
Notice: Use of undefined constant WP_DEBUG - assumed 'WP_DEBUG' in /vendor/hellonico/timber-dump-extension/functions.php on line 13

**Comment by nlemoine** [comment]
Weird, `WP_DEBUG` should be defined by WordPress. Can you tell me more on your setup?

**Comment by philiprabbett** [comment]
I use Capistrano for deployment via cli: https://github.com/capistrano/capistrano

Error occurs mostly when using WP-CLI however

**Comment by ErikFontanel** [comment]
I encounter the same issue; I believe it's because I don't have WP defined as a composer dependency (but I do use `phpdotenv` and thus timber-dump-extension gets auto loaded before WP_DEBUG is defined. The error is shown in WP-CLI because it is possible to use WP-CLI without Wordpress loaded (to install Wordpress ;)).

The fix is trivial, add `defined('WP_DEBUG')` to https://github.com/nlemoine/timber-dump-extension/blob/master/functions.php#L13.

**Comment by nlemoine** [comment]
Ok, I get it now. 

I'll add a fix for this. 

Although this extension is best placed in the `require-dev` section of your `composer.json` file.
