### ISSUE TITLE
Conflict with Twig\Extension ?

### ISSUE THREAD

**Issue by arnolem** [nlemoine/timber-dump-extension#4]
Hello,

I installed this extension using composer
```bash
composer require hellonico/timber-dump-extension
```
The ``dd()`` function works fine but using ``{{ dump()}}`` does not show the coloring 

Timber installed the ``dump()`` extension by default and it is always this one that is called
``\vendor\twig\twig\Extension\DebugExtension.php:30``
```php
        return [
            new TwigFunction('dump', 'twig_var_dump', ['is_safe' => $isDumpOutputHtmlSafe ? ['html'] : [], 'needs_context' => true, 'needs_environment' => true, 'is_variadic' => true]),
        ];
```

How to replace the previous extension installed by default with Timber? 

Thanks

**Comment by arnolem** [comment]
I use **bedrock**

**WP_DEBUG** constant is defined with ``Config::define('WP_DEBUG', true);`` but your plugin is load before this.

```php
// WP_DEBUG is not defined here
if (defined('WP_DEBUG') && WP_DEBUG && function_exists('add_filter')) {
    add_filter('timber/loader/twig', sprintf('%s\\add_dump_extension', __NAMESPACE__));
}
```

**Comment by nlemoine** [comment]
Salut @arnolem, 

You're probably loading this extension too early because you `composer required` at the root level (Bedrock). If you're using Timber, you should use another `composer.json` at theme/plugin level and use it in a plugin/functions.php file which is included later in the WP boot process. 

If this is an issue for you, you can still use the standalone package (`hellonico/twig-dump-extension`) and register the extension yourself.

**Comment by arnolem** [comment]
Thanks, it's perfect!
I load ``hellonico/twig-dump-extension`` manualy on **functions.php**

```php
add_filter('timber/loader/twig', function($twig){
    $twig->addExtension(new DumpExtension());
    return $twig;
});
```

👍
